// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8WfYAtefNJziOc40w192k4k5njRRWng',
    appId: '1:550282978216:web:5a0f7c46129ba3e5e6f39d',
    messagingSenderId: '550282978216',
    projectId: 'miralo-app',
    authDomain: 'miralo-app.firebaseapp.com',
    databaseURL: 'https://miralo-app-default-rtdb.firebaseio.com',
    storageBucket: 'miralo-app.firebasestorage.app',
    measurementId: 'G-7SD5P7B6DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr0-7wTr_yAxAVOZfWnLFb1yHFBNuEMqo',
    appId: '1:550282978216:android:53ee9651fac071c4e6f39d',
    messagingSenderId: '550282978216',
    projectId: 'miralo-app',
    databaseURL: 'https://miralo-app-default-rtdb.firebaseio.com',
    storageBucket: 'miralo-app.firebasestorage.app',
  );
}
